### ISSUE TITLE
Error: zsh:1: command not found: command_to_run_on_playback_events

### ISSUE THREAD

**Issue by kaijuh** [Spotifyd/spotifyd#1008]
**Description**
I keep getting a Error: zsh:1: command not found: command_to_run_on_playback_events

I followed all of the instructions I could find so I am sort of stuck of why I keep getting those messages. I get audio and my spotify-tui works as well.

I am just unsure how to solve the error messages I am getting

**Logs**
<details><summary>Click to show logs</summary>

```
Loading config from "/Users/firespace/.config/spotifyd/spotifyd.conf"
No proxy specified
Using software volume controller.
Failed to register IPv6 receiver: Os { code: 49, kind: AddrNotAvailable, message: "Can't assign requested address" }
Checking keyring for password
Connecting to AP "guc3-accesspoint-a-135l.ap.spotify.com:443"
Authenticated as "****" !
Country: "US"
Running "command_to_run_on_playback_events" using "/bin/zsh" with environment variables {"VOLUME": "58981", "PLAYER_EVENT": "volumeset"}
Failed to execute "command_to_run_on_playback_events" using "/bin/zsh". Error: zsh:1: command not found: command_to_run_on_playback_events

Running "command_to_run_on_playback_events" using "/bin/zsh" with environment variables {"PLAY_REQUEST_ID": "0", "TRACK_ID": "2kaqfutZitfOiNOWN6JH64", "PLAYER_EVENT": "preload"}
Loading <Saga Menuette> with Spotify URI <spotify:track:3EwA8gI0oi0vtmIBZBjGRQ>
<Saga Menuette> (111207 ms) loaded

```

</details>

**Compilation flags** 
- [ ] dbus_mpris
- [ ] dbus_keyring
- [] alsa_backend
- [x] portaudio_backend
- [ ] pulseaudio_backend
- [ ] rodio_backend

**Versions (please complete the following information):**

- OS: MacOS
- Spotifyd: stable 0.3.2

**Comment by MasonWeaver** [comment]
Can you post your spotifyd.conf file? Please be sure to remove any sensitive information from it before posting it.

**Comment by TheMayhem6328** [comment]
I have the same problem here:

`Failed to execute "command_to_run_on_playback_events" using "/bin/zsh". Error: zsh:1: command not found: command_to_run_on_playback_events`

(My shell is set to `/bin/zsh` - I am running Arch x86_64)

This is preventing me from setting volume through app

I attached my config below

`~/.config/spotifyd`
```toml
[global]
# Your Spotify account name.
username = "%Uname"

# Your Spotify account password.
password = "%Passwd"

# A command that gets executed and can be used to
# retrieve your password.
# The command should return the password on stdout.
#
# This is an alternative to the `password` field. Both
# can't be used simultaneously.
password_cmd = ""

# If set to true, `spotifyd` tries to look up your
# password in the system's password storage.
#
# This is an alternative to the `password` field. Both
# can't be used simultaneously.
use_keyring = false

#
# If set to true, `spotifyd` tries to bind to the session dbus
# and expose MPRIS controls. When running headless, without a dbus session,
# then set this to false to avoid binding errors
#
use_mpris = false

# The audio backend used to play the your music. To get
# a list of possible backends, run `spotifyd --help`.
backend = "alsa" # use portaudio for macOS [homebrew]

# The alsa audio device to stream audio to. To get a
# list of valid devices, run `aplay -L`,
device = "hw:0" # omit for macOS

# The alsa control device. By default this is the same
# name as the `device` field.
control = "hw:0" # omit for macOS

# The alsa mixer used by `spotifyd`.
mixer = "PCM"  # omit for macOS

# The volume controller. Each one behaves different to
# volume increases. For possible values, run
# `spotifyd --help`.
volume_controller = "alsa"  # use softvol for macOS

# A command that gets executed in your shell after each song changes.
on_song_change_hook = "command_to_run_on_playback_events"

# The name that gets displayed under the connect tab on
# official clients. Spaces are not allowed!
device_name = "daemon"

# The audio bitrate. 96, 160 or 320 kbit/s
bitrate = 320

# The directory used to cache audio data. This setting can save
# a lot of bandwidth when activated, as it will avoid re-downloading
# audio files when replaying them.
#
# Note: The file path does not get expanded. Environment variables and
# shell placeholders like $HOME or ~ don't work!
cache_path = "/home/mayhem6328/.temp.spotifyd"

# If set to true, audio data does NOT get cached.
no_audio_cache = false

# Volume on startup between 0 and 100
# NOTE: This variable's type will change in v0.4, to a number (instead of string)
initial_volume = "90"

# If set to true, enables volume normalisation between songs.
volume_normalisation = true

# The normalisation pregain that is applied for each song.
normalisation_pregain = -10

# The port `spotifyd` uses to announce its service over the network.
zeroconf_port = 6328

# The proxy `spotifyd` will use to connect to spotify.
proxy = ""

# The displayed device type in Spotify clients.
# Can be unknown, computer, tablet, smartphone, speaker, t_v,
# a_v_r (Audio/Video Receiver), s_t_b (Set-Top Box), and audio_dongle.
device_type = "a_v_r"
```

I don't get any of that when running `spotifyd -u %Uname -p %Passwd --no-daemon`
