### ISSUE TITLE
Client Name Change

### ISSUE THREAD

**Issue by Bazmundi** [Spotifyd/spotifyd#1029]
**Is your feature request related to a problem? Please describe.**
I installed spotifyd daemon via snap thanks.   Found it from my spotify app on my android phone!  Noticed it was on network as spotifyd, obviously.    Would like to change this to device name its running on, as I will be setting up a number of RPi with the client around the house.

**Describe the solution you'd like**
Provide a means to change device name reported by client on spotify app.

**Describe alternatives you've considered**
Hack the snap to hard code client name per client.
Hack the installed snap config to force the client name from spotifyd to the device name.
Prefer a gentle means to set this. (May be via some route I am yet to find).

**Comment by eladyn** [comment]
I have never used snap before, but in theory you should be able to either modify the config file (which you might have tried already according to your message) or pass the cli argument `--device-name "your_custom_name"` or just `-d "your_custom_name"`.

The relevant config entry would look like this:

```toml
[global]

# The name that gets displayed under the connect tab on
# official clients. Spaces are not allowed!
device_name = "device_name_in_spotify_connect"
```
from [here](https://spotifyd.github.io/spotifyd/config/File.html)

Sorry if this totally missed your question and/or does not work with snap.
