### ISSUE TITLE
Install on Raspberry Pi Zero W2

### ISSUE THREAD

**Issue by matejliska** [Spotifyd/spotifyd#1051]
**My first bug report, be patient w me pls**

I was following this instruction on: https://spotifyd.github.io/spotifyd/installation/Raspberry-Pi.html

And after> wget https://github.com/Spotifyd/spotifyd/releases/download/v0.3.3/spotifyd-linux-armv6-slim.tar.gz
untar it with> tar -xvzf  spotifyd-linux-armv6-slim.tar.gz
and run with> ./spotifyd --no-daemon

terminal Write me this error:

/------------------------------------------------------------------------------/
pi@raspberrypi:~ $ ./spotifyd --no-daemon
Loading config from "/home/pi/.config/spotifyd/spotifyd.conf"
Error: 
   0: could not load the config file
   1: invalid TOML value, did you mean to use a quoted string? at line 5 column 10

Location:
   src/config.rs:478

note:
   the config format should be valid TOML
   we recently changed the config format, see https://github.com/Spotifyd/spotifyd/issues/765

Backtrace omitted.
Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
pi@raspberrypi:~ $ 

I will ask for advice with this problem, as soon as possible. Thnx a lot.

**Versions**

- OS: Raspbian
- HW: RP3A0 - Quad-core 64-bit Arm Cortex A53 CPU
- Spotifyd: 0.3.3

**Comment by eladyn** [comment]
Hi and welcome!

As the error message indicates, `spotifyd` has trouble parsing the config file. I assume that you copied it from the installation instructions that you linked to.

The copied file is not valid in its documented form as you need to change some values:

- `device` needs to be a quoted string with the alsa device name. Alternatively, you can just leave it out.
- `bitrate` needs to be either `96` or `160` or `320`.
- Change the other values to suit your needs.

The following file should get past the errors (make sure that you replace `USER` and `PASS` with your values):

```toml
[global]
username = "USER"
password = "PASS"
backend = "alsa"
mixer = "PCM"
volume-controller = "alsa" # or alsa_linear, or softvol
device_name = "my_spotifyd"
bitrate = 320
volume-normalisation = true
normalisation-pregain = -10
```

Maybe this helps to get your installation working! If you have any further questions, feel free to ask! :smiley: 

Edit: see also [this issue](https://github.com/Spotifyd/spotifyd/issues/1031#issue-1088063205)
