### ISSUE TITLE
Panic when loading track

### ISSUE THREAD

**Issue by tmplt** [Spotifyd/spotifyd#897]
**Description**
spotifyd v0.3.0 panics when I play a song.

**To Reproduce**
1. `nix run -f channel:nixpkgs-unstable spotifyd`.
2. Write into `~/.config/spotifyd/spotifyd.conf`:
    ```toml
    [global]
    username = "[REDACTED]"
    password = "[REDACTED]"
    backend = "pulseaudio"
    device_name = "perscitia"
    bitrate = 320
    no_audio_cache = true
    device_type = "computer"
    ```

3. Start spotifyd via `spotifyd --no-daemon`.
4. Select spotifyd via Connect and play a track in a playlist.
5. Observe panic.

**Logs**
```
Loading config from "/home/tmplt/.config/spotifyd/spotifyd.conf"
No proxy specified
Using software volume controller.
Connecting to AP "gew1-accesspoint-e-bhhz.ap.spotify.com:443"
Authenticated as "[REDACTED]" !
Country: "SE"
Loading <Nuclear> with Spotify URI <spotify:track:754WgEesWgssZG3XzU9XcG>
Caught panic with message: attempted to zero-initialize type `librespot_tremor::tremor_sys::ov_callbacks`, which is invalid
Caught panic with message: called `Result::unwrap()` on an `Err` value: "SendError(..)"
```

`--verbose` spits out a lot of info. I have yet to go through it to redact any eventual credentials.

**Versions (please complete the following information):**

- OS: NixOS
- Spotifyd: v0.3.0
- cargo: N/A
