### ISSUE TITLE
Audio backend issue

### ISSUE THREAD

**Issue by tommyalatalo** [Spotifyd/spotifyd#995]
I can't find any instructions for spotifyd on how to connect a bluetooth headset.

Following the current instructions I should be able to find an audio device using `aplay -L`, but there are no bluetooth devices shown by that command:

```
❯ aplay -L
null
    Discard all samples (playback) or generate zero samples (capture)
samplerate
    Rate Converter Plugin Using Samplerate Library
speexrate
    Rate Converter Plugin Using Speex Resampler
jack
    JACK Audio Connection Kit
oss
    Open Sound System
pipewire
    PipeWire Sound Server
pulse
    PulseAudio Sound Server
speex
    Plugin using Speex DSP (resample, agc, denoise, echo, dereverb)
upmix
    Plugin for channel upmix (4,6,8)
vdownmix
    Plugin for channel downmix (stereo) with a simple spacialization
default
    Default ALSA Output (currently PipeWire Media Server)
sysdefault:CARD=Loopback
    Loopback, Loopback PCM
    Default Audio Device
front:CARD=Loopback,DEV=0
    Loopback, Loopback PCM
    Front output / input
surround21:CARD=Loopback,DEV=0
    Loopback, Loopback PCM
    2.1 Surround output to Front and Subwoofer speakers
surround40:CARD=Loopback,DEV=0
    Loopback, Loopback PCM
    4.0 Surround output to Front and Rear speakers
surround41:CARD=Loopback,DEV=0
    Loopback, Loopback PCM
    4.1 Surround output to Front, Rear and Subwoofer speakers
surround50:CARD=Loopback,DEV=0
    Loopback, Loopback PCM
    5.0 Surround output to Front, Center and Rear speakers
surround51:CARD=Loopback,DEV=0
    Loopback, Loopback PCM
    5.1 Surround output to Front, Center, Rear and Subwoofer speakers
surround71:CARD=Loopback,DEV=0
    Loopback, Loopback PCM
    7.1 Surround output to Front, Center, Side, Rear and Woofer speakers
usbstream:CARD=Loopback
    Loopback
    USB Stream Output
sysdefault:CARD=PCH
    HDA Intel PCH, ALC289 Analog
    Default Audio Device
front:CARD=PCH,DEV=0
    HDA Intel PCH, ALC289 Analog
    Front output / input
surround21:CARD=PCH,DEV=0
    HDA Intel PCH, ALC289 Analog
    2.1 Surround output to Front and Subwoofer speakers
surround40:CARD=PCH,DEV=0
    HDA Intel PCH, ALC289 Analog
    4.0 Surround output to Front and Rear speakers
surround41:CARD=PCH,DEV=0
    HDA Intel PCH, ALC289 Analog
    4.1 Surround output to Front, Rear and Subwoofer speakers
surround50:CARD=PCH,DEV=0
    HDA Intel PCH, ALC289 Analog
    5.0 Surround output to Front, Center and Rear speakers
surround51:CARD=PCH,DEV=0
    HDA Intel PCH, ALC289 Analog
    5.1 Surround output to Front, Center, Rear and Subwoofer speakers
surround71:CARD=PCH,DEV=0
    HDA Intel PCH, ALC289 Analog
    7.1 Surround output to Front, Center, Side, Rear and Woofer speakers
hdmi:CARD=PCH,DEV=0
    HDA Intel PCH, HDMI 0
    HDMI Audio Output
hdmi:CARD=PCH,DEV=1
    HDA Intel PCH, HDMI 1
    HDMI Audio Output
hdmi:CARD=PCH,DEV=2
    HDA Intel PCH, HDMI 2
    HDMI Audio Output
hdmi:CARD=PCH,DEV=3
    HDA Intel PCH, HDMI 3
    HDMI Audio Output
hdmi:CARD=PCH,DEV=4
    HDA Intel PCH, HDMI 4
    HDMI Audio Output
usbstream:CARD=PCH
    HDA Intel PCH
    USB Stream Output
```

My bluetooth device is however shown by `pactl`:

```
❯ pactl list cards short
45      alsa_card.pci-0000_00_1f.3      alsa
46      alsa_card.platform-snd_aloop.0  alsa
103     bluez_card.00_1B_66_88_1D_52    module-bluez5-device.c
```

```
❯ pactl list sinks short
53      alsa_output.pci-0000_00_1f.3.analog-stereo      PipeWire        s32le 2ch 48000Hz       SUSPENDED
55      alsa_output.platform-snd_aloop.0.analog-stereo  PipeWire        s32le 2ch 48000Hz       SUSPENDED
114     bluez_output.00_1B_66_88_1D_52.a2dp-sink        PipeWire        s24le 2ch 48000Hz       SUSPENDED
```

Is there a way to specify the bluetooth device for spotifyd?
If I open up `alsamixer` then the default master volume that it opens up into controls the bluetooth headset volume correctly, `alsamixer` states the card and chip as PipeWire in that view, but setting `pipewire` as the device under the `alsa` backend doesn't work either.

**Comment by Icelk** [comment]
This does not seems to be a spotifyd issue. Consider using `pulsemixer` to control pulseaudio instead of `aplay`, as that only outputs to pipewire, which controls the audio.

**Comment by tommyalatalo** [comment]
I think spotifyd should have documentation for how to configure a bluetooth headset to work, since they're quite common these days, but don't seem to show up with `aplay` as devices. It's not possible to configure this by following the existing instructions. 

I installed `pulsemixer`, but I don't see what it should be telling me to get me closer to a working configuration. If `pulsemixer` is the way to go for bluetooth somehow, could you elaborate on your suggestion?

**Comment by Icelk** [comment]
This is linux audio and bluetooth, not spotifyd. The audio output from Pipewire, which gets it's audio from spotifyd, is handed over to Bluez. That then sends it to your headset over bluetooth.
You should be able to set the `Bluez` output in `pulsemixer` as default, and see `spotifyd` move to under it. Make sure the channel isn't muted.
An useful article:
https://wiki.archlinux.org/title/Bluetooth

**Comment by tommyalatalo** [comment]
I can see my bluetooth headset in pulsemixer and set it to the default, change volume etc, but how do I configure that device for spotifyd to use?

Currently my config is the below, with `sink-73` stated as the ID by `pulsemixer -l`, but spotifyd warns at the start that it `Couldn't read volume from alsa device with name "sink-73".`, I also tried with the stated `Name` which is `MOMENTUM M2 AEBT`, but that just ends up with the same warning. Where do I find the device and control values that I need to give spotifyd? 
 
```
# If set to true, `spotifyd` tries to bind to the session dbus
# and expose MPRIS controls. When running headless, without a dbus session,
# then set this to false to avoid binding errors
#
use_mpris = false

# The audio backend used to play the your music. To get
# a list of possible backends, run `spotifyd --help`.
backend = "pulseaudio"

# The alsa audio device to stream audio to. To get a
# list of valid devices, run `aplay -L`,
device = "sink-73"  # omit for macOS

# The alsa control device. By default this is the same
# name as the `device` field.
control = "sink-73"  # omit for macOS

# The alsa mixer used by `spotifyd`.
mixer = "PCM"

# The volume controller. Each one behaves different to
# volume increases. For possible values, run
# `spotifyd --help`.
volume_controller = "alsa"  # use softvol for macOS
```

**Comment by Icelk** [comment]
Try commenting out `mixer`, `control`, and `device`.

If that doesn't work, change `volume_controller = "alsa"` to `softvol`.

The problem here is spotifyd trying to attach to ALSA to get the volume, but you use Pipewire, which captures ALSA.

Hope it works!

**Comment by tommyalatalo** [comment]
> Try commenting out `mixer`, `control`, and `device`.
> 
> If that doesn't work, change `volume_controller = "alsa"` to `softvol`.
> 
> The problem here is spotifyd trying to attach to ALSA to get the volume, but you use Pipewire, which captures ALSA.
> 
> Hope it works!

Hmm, unfortunately not. Here's what I have:

```toml
#
# If set to true, `spotifyd` tries to bind to the session dbus
# and expose MPRIS controls. When running headless, without a dbus session,
# then set this to false to avoid binding errors
#
use_mpris = false

# The audio backend used to play the your music. To get
# a list of possible backends, run `spotifyd --help`.
backend = "pulseaudio"

# The alsa audio device to stream audio to. To get a
# list of valid devices, run `aplay -L`,
# device = "bluez_card.00_1B_66_88_1D_52"  # omit for macOS

# The alsa control device. By default this is the same
# name as the `device` field.
# control = "sink-73"  # omit for macOS

# The alsa mixer used by `spotifyd`.
# mixer = "PCM"

# The volume controller. Each one behaves different to
# volume increases. For possible values, run
# `spotifyd --help`.
volume_controller = "softvol"  # use softvol for macOS
```

I tried setting the `volume_controller` to both `softvol` and `alsa`, but both result in this repeated error:

```
Sep 06 18:47:41 arch spotifyd[1271305]: Could not write audio: Not connected to pulseaudio
Sep 06 18:47:41 arch spotifyd[1271305]: Could not start audio: Connection refused
```

Does this give you any idea of what's still missing? I'm using `spt` as the client if that makes any difference.
